#ifndef __VNCDEFS_H__
#define __VNCDEFS_H__

#define LIBVNCSERVER_HAVE_LIBJPEG 
#define LIBVNCSERVER_HAVE_LIBZ 

#define LIBVNCSERVER_HAVE_GETTIMEOFDAY
#define LIBVNCSERVER_HAVE_NETINET_IN_H

#define LIBVNCSERVER_HAVE_FCNTL_H

/* Define to the full name and version of this package. */
#define LIBVNCSERVER_PACKAGE_STRING  "@FULL_PACKAGE_NAME@ @PACKAGE_VERSION@"

/* Define to the version of this package. */
#define LIBVNCSERVER_PACKAGE_VERSION  "@PACKAGE_VERSION@"
#define LIBVNCSERVER_VERSION "@PACKAGE_VERSION@"
#define LIBVNCSERVER_VERSION_MAJOR "@VERSION_MAJOR@"
#define LIBVNCSERVER_VERSION_MINOR "@VERSION_MINOR@"
#define LIBVNCSERVER_VERSION_PATCHLEVEL "@VERSION_PATCHLEVEL@"

#endif		//__VNCDEFS_H__
